version: 2
jobs:
  test:
    docker:
      - image: cypress/base
    steps:
      - checkout
      # restore folders with npm dependencies and cypress binary
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      # install npm dependencies and cypress binary
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run: yarn cy:verify
      # save npm dependencies and cypress binary
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run tests
          command: yarn test:cy
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build:
    jobs:
      - test
